// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumEnvoyMixes implements CiliumEnvoyMixInterface
type FakeCiliumEnvoyMixes struct {
	Fake *FakeCiliumV2alpha1
}

var ciliumenvoymixesResource = schema.GroupVersionResource{Group: "cilium.io", Version: "v2alpha1", Resource: "ciliumenvoymixes"}

var ciliumenvoymixesKind = schema.GroupVersionKind{Group: "cilium.io", Version: "v2alpha1", Kind: "CiliumEnvoyMix"}

// Get takes name of the ciliumEnvoyMix, and returns the corresponding ciliumEnvoyMix object, and an error if there is any.
func (c *FakeCiliumEnvoyMixes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumEnvoyMix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ciliumenvoymixesResource, name), &v2alpha1.CiliumEnvoyMix{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyMix), err
}

// List takes label and field selectors, and returns the list of CiliumEnvoyMixes that match those selectors.
func (c *FakeCiliumEnvoyMixes) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumEnvoyMixList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ciliumenvoymixesResource, ciliumenvoymixesKind, opts), &v2alpha1.CiliumEnvoyMixList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumEnvoyMixList{ListMeta: obj.(*v2alpha1.CiliumEnvoyMixList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumEnvoyMixList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumEnvoyMixes.
func (c *FakeCiliumEnvoyMixes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ciliumenvoymixesResource, opts))
}

// Create takes the representation of a ciliumEnvoyMix and creates it.  Returns the server's representation of the ciliumEnvoyMix, and an error, if there is any.
func (c *FakeCiliumEnvoyMixes) Create(ctx context.Context, ciliumEnvoyMix *v2alpha1.CiliumEnvoyMix, opts v1.CreateOptions) (result *v2alpha1.CiliumEnvoyMix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ciliumenvoymixesResource, ciliumEnvoyMix), &v2alpha1.CiliumEnvoyMix{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyMix), err
}

// Update takes the representation of a ciliumEnvoyMix and updates it. Returns the server's representation of the ciliumEnvoyMix, and an error, if there is any.
func (c *FakeCiliumEnvoyMixes) Update(ctx context.Context, ciliumEnvoyMix *v2alpha1.CiliumEnvoyMix, opts v1.UpdateOptions) (result *v2alpha1.CiliumEnvoyMix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ciliumenvoymixesResource, ciliumEnvoyMix), &v2alpha1.CiliumEnvoyMix{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyMix), err
}

// Delete takes name of the ciliumEnvoyMix and deletes it. Returns an error if one occurs.
func (c *FakeCiliumEnvoyMixes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(ciliumenvoymixesResource, name, opts), &v2alpha1.CiliumEnvoyMix{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumEnvoyMixes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ciliumenvoymixesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumEnvoyMixList{})
	return err
}

// Patch applies the patch and returns the patched ciliumEnvoyMix.
func (c *FakeCiliumEnvoyMixes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumEnvoyMix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ciliumenvoymixesResource, name, pt, data, subresources...), &v2alpha1.CiliumEnvoyMix{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyMix), err
}
