// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumEnvoyMixLister helps list CiliumEnvoyMixes.
// All objects returned here must be treated as read-only.
type CiliumEnvoyMixLister interface {
	// List lists all CiliumEnvoyMixes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyMix, err error)
	// Get retrieves the CiliumEnvoyMix from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumEnvoyMix, error)
	CiliumEnvoyMixListerExpansion
}

// ciliumEnvoyMixLister implements the CiliumEnvoyMixLister interface.
type ciliumEnvoyMixLister struct {
	indexer cache.Indexer
}

// NewCiliumEnvoyMixLister returns a new CiliumEnvoyMixLister.
func NewCiliumEnvoyMixLister(indexer cache.Indexer) CiliumEnvoyMixLister {
	return &ciliumEnvoyMixLister{indexer: indexer}
}

// List lists all CiliumEnvoyMixes in the indexer.
func (s *ciliumEnvoyMixLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyMix, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumEnvoyMix))
	})
	return ret, err
}

// Get retrieves the CiliumEnvoyMix from the index for a given name.
func (s *ciliumEnvoyMixLister) Get(name string) (*v2alpha1.CiliumEnvoyMix, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumenvoymix"), name)
	}
	return obj.(*v2alpha1.CiliumEnvoyMix), nil
}
