name: Documentation Updates

on:
  pull_request: {}
  push:
    branches:
      - v1.9

jobs:
  build-html:
    name: Validate & Build HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cilium/docs-builder:latest
        with:
          entrypoint: ./Documentation/check-build.sh
          args: html
      - name: Send slack notification
        if: ${{ (cancelled() || failure()) && (github.event_name == 'schedule' || github.event_name == 'push') }}
        uses: 8398a7/action-slack@28ba43ae48961b90635b50953d216767a6bea486
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
