name: Images
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - v1.9

jobs:
  lint:
    if: github.repository == 'cilium/cilium'
    name: Lint image build logic
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://docker.io/cilium/image-maker:bc81755ec8f6c5afcb10a416cef73f99a35fee2c
        name: Run make lint
        with:
          entrypoint: make
          args: -C images lint
      - uses: docker://docker.io/cilium/image-maker:bc81755ec8f6c5afcb10a416cef73f99a35fee2c
        name: Check if runtime and builder images are up-to-date
        with:
          entrypoint: make
          args: -C images check-runtime-image check-builder-image
